services:
  eureka-server:
    build: .
    image: eureka:1.0.0
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose up --build -d
