server:
  port: 8761

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
